### ISSUE TITLE
[1.14.4] Better Advancements

### ISSUE THREAD

**Issue by Rotzo** [Unity-Resource-Pack/Unity-Dark#11]
If you find the time, i would be happy about this one:

https://www.curseforge.com/minecraft/mc-mods/better-advancements

**Comment by MelanX** [comment]
I would make a PR but for that, the other PRs needs to be accepted. It's because all mods with advancements need an update and it's easier when everything is merged.

**Comment by Rotzo** [comment]
Ok. I just noticed that CyanideX shared his photoshop atn. in the curseforge comments, so i have done it myself. If anyone is interested, it's here: https://www.dropbox.com/sh/rbs9xp6mmwwbry5/AACvnp1vQGhWNG-ZBVwU93sTa?dl=0

**Comment by MelanX** [comment]
You forgot the language files of each mod which is already in the this resource pack and includes advancements
