### ISSUE TITLE
1.16.1 Mekanism/JEI: the material amounts in some recipes display as "%,d"

### ISSUE THREAD

**Issue by mbfrog** [Unity-Resource-Pack/Unity-Dark#26]
This can be seen in the recipes for the Electrolytic Separator: all amounts for the main ingredient (Water, Heavy Water, Brine), display as "%,d". This is the same in the Evaporation Chamber where all amounts appear the same way for both available recipes (Brine -> Lithium, Water->Brine). This can also be seen in the recipes for the Rotary Condensentrator where the amounts for liquids are affected as well. Haven't checked any other place.

**Comment by CyanideX** [comment]
Fixed in 349ab94 🙂
