### ISSUE TITLE
[1.14.4] Iron, Crystal and Copper chests not working correctly

### ISSUE THREAD

**Issue by hickorysb** [Unity-Resource-Pack/Unity-Dark#27]
**Describe the Issue**
The GUI gets cut off and the inventory slots don't line up with the GUI background.

**To Reproduce**
- Place copper, crystal, or iron chest or their shulker box counterpart, then open their GUI.

**Expected Behavior**
It should line up the inventory slots with the GUI background

**Screenshots**
![image](https://user-images.githubusercontent.com/44131234/89131425-387d5e80-d4b9-11ea-918a-a2c668faf9e6.png)

**Additional Context**
- Using OptiFine
- Iron Chests and JEI are installed

**Comment by CyanideX** [comment]
Thanks for pointing this out. It looks like Iron Chests changed their GUIs between 1.14 and 1.15. 😞 I guess I will have to mark the pack as incompatible with 1.14.
