### ISSUE TITLE
[1.16.1] Unity dark hides Industrial Foregoing's redstone control

### ISSUE THREAD

**Issue by novaexe** [Unity-Resource-Pack/Unity-Dark#28]
![2020-08-22_19 59 15](https://user-images.githubusercontent.com/69226867/90967924-f772db80-e4b3-11ea-9d5c-5b7ac91dad4b.png)

![2020-08-22_20 05 48](https://user-images.githubusercontent.com/69226867/90967929-02c60700-e4b4-11ea-87a0-799138291123.png)

**Comment by Buuz135** [comment]
no u

**Comment by CyanideX** [comment]
Turns out it was Titanium (again, I blame @Buuz135) but I have fixed it in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/506e7ef71d9321b4ee03b3228c097427642bc083
