### ISSUE TITLE
[1.16] (WIP) Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by tikiMC** [Unity-Resource-Pack/Unity-Dark#30]
Would love to see the cosmetic armor reworked screen work with this awesome pack so it doesn't blind my eyes, every time. Aswell I use better advancements and it would also be cool if that had support.

**Comment by CyanideX** [comment]
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

**Comment by omeranha** [comment]
Soo, ill put my work here, as you said
[cosmeticarmorreworked.zip](https://github.com/Unity-Resource-Pack/Unity-Dark/files/5250081/cosmeticarmorreworked.zip)
