### ISSUE TITLE
[1.16] (WIP) Applied Energetics 2

### ISSUE THREAD

**Issue by omeranha** [Unity-Resource-Pack/Unity-Dark#32]
i'm playing and boom, applied energistics 2 don't have support in this resource pack, sooo, i used your dark colors and make my part of applied (obviously, only for my use).isn't 100% yet, but i want to help you with applied and why not, with other mods :D
if you accept my help, send me a message on Discord: oMeranha#0007

below, the crafting terminal of applied ^^
![crafting](https://user-images.githubusercontent.com/53233626/93530874-b0420400-f914-11ea-9985-ff5c36b332f7.png)

**Comment by CyanideX** [comment]
Did you use the Photoshop action we provided in the readme? 🙂 

https://www.dropbox.com/s/ggz5aveq0vdixvz/Unity%20Dark%20Mode.atn?dl=0

Are you working on this for 1.16?

**Comment by omeranha** [comment]
i'm using paint.net atm, i can use photoshop if you want
yes, 1.16.1

**Comment by CyanideX** [comment]
I only recommend the action because it converts all of the GUI textures exactly and then applies the same noise. Some GUIs will require certain elements to be fixed manually but the action will make the process much easier, especially when converting entire folders. 😛

**Comment by omeranha** [comment]
oh right, ty for the help :)

**Comment by omeranha** [comment]
OOOH, thats fast, i spend 30 minutes to complete my crafting and the action completed in 1 second, lul

**Comment by omeranha** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/53233626/93534197-fef29c80-f91a-11ea-8e2d-603462072cdd.png)
huh, i think it's something wrong

**Comment by omeranha** [comment]
last thing, the words because of the dark color are illegible, how can I solve this problem?

**Comment by CyanideX** [comment]
Look at the example lang files in the pack. You have to change all the container GUI text to include the Minecraft color code symbol.

**Comment by omeranha** [comment]
Right, i completed my part, only thing, i think it's a bug from applied lang code, the ME Fluid Terminal don't have a line code to change color in gui, only this. In my tests all is going good
[appliedenergistics2.zip](https://github.com/Unity-Resource-Pack/Unity-Dark/files/5242647/appliedenergistics2.zip)

**Comment by mkaito** [comment]
There seems to be something going on with the states.png asset, but I'm not sure what it's trying to display.

![image](https://user-images.githubusercontent.com/20434/101534284-d5339980-398e-11eb-98bd-fc0531717799.png)

**Comment by mkaito** [comment]
I've used the zip submitted by @omeranha for a bit, and felt it lacking in contrast a little bit. I'm making some adjustments. I'll submit a PR if I get it somewhere pleasant.

**Comment by CyanideX** [comment]
If you have Photoshop, using [this action](https://www.dropbox.com/s/ggz5aveq0vdixvz/Unity%20Dark%20Mode.atn?dl=0) will do most of work for you.

**Comment by mkaito** [comment]
I'm using Krita. Photoshop doesn't really run very well on Linux. What does that action do? Is it important?

**Comment by CyanideX** [comment]
Well, yes, it is important. The action will automatically generate the dark GUI from the standard colors.

See example here:
https://streamable.com/w9j2tf

**Comment by mkaito** [comment]
Well, that's awfully convenient... Let me see if I can get PS running.

**Comment by CyanideX** [comment]
Thank you both for your interest in the pack and for your contributions. ❤️
