### ISSUE TITLE
[1.16] (WIP) Cosmetic armor Reworked

### ISSUE THREAD

**Issue by omeranha** [Unity-Resource-Pack/Unity-Dark#33]
Hey, It's me again :p
i'm also completed the cosmetic armor inventory support, if you want
the lang file isn't necessary because the original is already white.
[cosmeticarmorreworked.zip](https://github.com/Unity-Resource-Pack/Unity-Dark/files/5245646/cosmeticarmorreworked.zip)

**Comment by ChloeDawn** [comment]
This is a duplicate of #30, please could you include your work in that thread instead? Thanks.
