### ISSUE TITLE
Permission to continue updating the Unity-Resource Pack

### ISSUE THREAD

**Issue by omeranha** [Unity-Resource-Pack/Unity-Dark#34]
I wanted to ask permission from the creator of the resource pack, so that I can continue updating the resource pack to version 1.16.3, because apparently, the resource pack will no longer be updated, it did not give more news after that day.
I'm getting several mods for dark, for my own use, but 2 people asked me to send the resource pack, so I ask your permission
either with the resource pack with a different name etc.
So far, thank you

**Comment by CyanideX** [comment]
Who told you the pack won't be updated? I have said repeatedly that I will be updating the pack as soon as I can.

You're more than welcome to submit your updates to the repo as a pull request and, if we approve of the changes, it can be merged for all to use and enjoy.
