### ISSUE TITLE
[0.7.0] The font color is very dark in lang PT-BR.

### ISSUE THREAD

**Issue by PequenaBR** [Unity-Resource-Pack/Unity-Dark#37]
The font color is very dark, you can hardly see it in some places, for example in the storage chest, inventory...

**(LANG: PT-BR)**

**Using:**  
Unity: Base - 2.4.0
Unity: Extras - 1.1.0
Unity: Modded - 1.3.0
Unity: Dark Edition - 0.7.0

![GKEl0p1](https://user-images.githubusercontent.com/54646457/106791231-6a6fa900-6633-11eb-8f1c-c03112412fd8.png)

**Comment by CyanideX** [comment]
I need assistance with other languages. 😢 Unfortunately, until I can get some help, I won't be able to fix non-english packs.
