### ISSUE TITLE
[1.16.X] Useful Backpacks

### ISSUE THREAD

**Issue by PequenaBR** [Unity-Resource-Pack/Unity-Dark#38]
**Suggestion**

Please add support for **Useful Backpacks** mod. Please

https://www.curseforge.com/minecraft/mc-mods/useful-backpacks

> ![image](https://user-images.githubusercontent.com/54646457/106791759-1addad00-6634-11eb-8477-a6ba60d2cc0c.png)

**Comment by ArchOwlen** [comment]
Working on it! Just not sure how to change the title color for this one #70
