### ISSUE TITLE
Colour of the letters

### ISSUE THREAD

**Issue by PerfektEli** [Unity-Resource-Pack/Unity-Dark#40]
Hi. The colours of the letters in the menu windoows  can't be read. The letter colours aree nearly the same colour as the background.

> `**Screenshots**

![2021-02-24_17 08 35](https://user-images.githubusercontent.com/79592963/109030131-d63db280-76c3-11eb-8332-cc5db1910f81.png)
![2021-02-24_17 08 15](https://user-images.githubusercontent.com/79592963/109030169-e0f84780-76c3-11eb-9044-6f5998e037da.png)

Optifine only, when it works and thaat is not atm.

thank you very much

bb Eli

**Comment by ChloeDawn** [comment]
That is not OptiFine only, I see another resource pack present in those screenshots. Make sure that resource pack is below Unity Dark in your resource pack list.

**Comment by CyanideX** [comment]
Unity Dark currently only supports English. There is no easy way to change all GUI text at once so it requires someone to manually change each one. You're welcome to add support for your language in a pull request and I will gladly add it to the pack. 🙂
