### ISSUE TITLE
[1.16] Trade menu errors

### ISSUE THREAD

**Issue by thokr** [Unity-Resource-Pack/Unity-Dark#41]
**Describe the Issue**
In the trade menus of villagers and wandering traders, the arrows and the rank text are blending in with the background, making them very hard to see.

**To Reproduce**
Open the trade menu of either a villager or a wandering trader.

**Expected Behavior**
Arrows and text in the trade menus should be clearly visible.

**Screenshots**
Villager menu:
![image](https://user-images.githubusercontent.com/20743993/110185939-20bcde80-7dea-11eb-9823-0c33e59b7abe.png)

Wandering trader menu:
![image](https://user-images.githubusercontent.com/20743993/110186022-5a8de500-7dea-11eb-832e-7fbab0384ff3.png)

**Additional Context**
I'm playing on 1.16.5. My game language is set to English. I'm using OptiFine, but the issue happens on vanilla as well.

**Comment by theogen-ratkin** [comment]
Also, the bar indicating experience gain from the purchase (the thing after the green bar) could be a little brighter too.

![image](https://user-images.githubusercontent.com/20743993/110191571-7ea7f100-7dff-11eb-9ad5-5ff20443465f.png)

**Comment by CyanideX** [comment]
#finallyFixed!
