### ISSUE TITLE
[Suggestion] Tinkers Construct

### ISSUE THREAD

**Issue by ChiefArug** [Unity-Resource-Pack/Unity-Dark#43]
**Suggestion**
After much awaiting Tinkers has finally been ported to 1.16! It would be great to have support for it!

**Comment by ChloeDawn** [comment]
Please use separate issue tickets for individual mod suggestions

**Comment by 19175** [comment]
Okay, wasn't sure wether to spam issues or condense them into one, will split them up then.

**Comment by ArchOwlen** [comment]
Working on it! 
#68

**Comment by CyanideX** [comment]
Will return to this when it comes to 1.19+.
