### ISSUE TITLE
[Suggestion] Thermal Series

### ISSUE THREAD

**Issue by ChiefArug** [Unity-Resource-Pack/Unity-Dark#44]
**Suggestion**
The Thermal Series of mods (Expansion, Innovation, ect)

Curseforge pages: [Expansion](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion) (The main "mod" with all the machines), [Foundation](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation/files), [Innovation](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation) (its only the magnet filter in here _I think_)

Finally [Locomotion](https://www.curseforge.com/minecraft/mc-mods/thermal-locomotion) and [Cultivation](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation) both of which have no GUI's but they are planning on developing them more later, so might have some then.

Note: I can split each of these up as well, but they are always used together so it doesn't make much sense(to me) to split them.

**Comment by CyanideX** [comment]
Added in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/0f66c8182ce3487e0a1e8b8941aef529512225f6

Better late than never, right? 😅

**Comment by ChiefArug** [comment]
🎉 
Why does it include the lang file?

**Comment by CyanideX** [comment]
So the GUI text isn't grey on grey?

**Comment by ChiefArug** [comment]
I can't see any special formatting chars in there that would change a gui title colour.

**Comment by CyanideX** [comment]
There aren't yet. But you asked why the lang file is there and that's why it is there.

**Comment by CyanideX** [comment]
I'm currently testing this shader which override the UI text color: https://github.com/Unity-Resource-Pack/Unity-Dark/commit/0627084c762e34237591b372cf5b9c6a52a02f87

If I do away with it, I will still need to edit lang files.

**Comment by ChiefArug** [comment]
Ah 👍️
