### ISSUE TITLE
[Suggestion] Astral Sorcery

### ISSUE THREAD

**Issue by ChiefArug** [Unity-Resource-Pack/Unity-Dark#45]
**Suggestion**
Astral Sorcery support would be great but they use thier marble texture instead of the classic light grey as a GUI background so it would make sense to use the sooty marble texture (although that may be too dark) for the dark version. If that's not possible it would be fine to just have regular dark GUI. 

Curseforge page: https://www.curseforge.com/minecraft/mc-mods/astral-sorcery/files

**Comment by CyanideX** [comment]
If there are ever any stylized GUIs in a mod, I will usually convert them to vanilla style. In the case of Unity Dark, I would do the same before converting it to the dark theme.

**Comment by CyanideX** [comment]
Could you also be sure to include links to the CurseForge projects so it's easier for me to grab when I do get around to this? :)
