### ISSUE TITLE
Is my **E** inventory supposed to be not dark?

### ISSUE THREAD

**Issue by CrypticWisdom62** [Unity-Resource-Pack/Unity-Dark#46]
**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior or see the issue:
- Example 1: Look at **x** block.
- Example 2: Open up **y** GUI.
- Example 3: At **z** o'clock, look at the sun, turn around 4.5 times, crouch, punch a tree.

**Expected Behavior**
A clear and concise description of what you expected to see. If it's just an issue with how it is implemented, offer suggestions on how this could be improved (also submit a suggestion next time).

**Screenshots**

**Additional Context**
Add any other context about the problem here. Do you happen to have any mods installed? Do you have any other resource packs enabled? Are you using OptiFine?

**Comment by ChloeDawn** [comment]
Fill out the issue template or we can't help you with your problem
