### ISSUE TITLE
[1.16.5] My player inventory is still regular color instead of dark

### ISSUE THREAD

**Issue by CrypticWisdom62** [Unity-Resource-Pack/Unity-Dark#48]
**Describe the Issue**
When I open my "E" inventory everything is still original instead of being dark

**To Reproduce**
Open your survival inventory

**Expected Behavior**
Player inventory should be in dark mode as well

**Screenshots**
![2021-05-16_20 28 31](https://user-images.githubusercontent.com/61163736/118406644-505b5300-b685-11eb-909b-c88bfe03028b.png)

**Additional Context**
Playing on 1.16.5, using the latest preview version of OF, using unity base and unity extras as well. Also, I have an ore outline texture pack but that is not active while using unity

**Comment by CyanideX** [comment]
Make sure Unity Dark is above other resource packs in the menu.

**Comment by CrypticWisdom62** [comment]
> Make sure Unity Dark is above other resource packs in the menu.

Thank you that seems to fix the issue, may I ask why the specific order?

**Comment by CyanideX** [comment]
It's just assigning priority to the resource packs; the packs on the top overwrite changes made by the others.

In this case, there are multiple resource packs making changes to the same GUI texture and only one of them can come out on top. 😛
