### ISSUE TITLE
[1.14.4] Apotheosis 

### ISSUE THREAD

**Issue by Boomflex** [Unity-Resource-Pack/Unity-Dark#5]
![image](https://user-images.githubusercontent.com/22868795/70564955-fd749680-1b88-11ea-9ca9-8855f94a641c.png)

**Comment by Boomflex** [comment]
https://www.curseforge.com/minecraft/mc-mods/apotheosis/download/2821146

**Comment by CyanideX** [comment]
Done in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/9f1aa870851f4232a270a9fbd9b514b0117d99b7
