### ISSUE TITLE
[1.16.5] When i place netherrac in the overworld it is pitch black

### ISSUE THREAD

**Issue by CrypticWisdom62** [Unity-Resource-Pack/Unity-Dark#50]
**Describe the Issue**
Placing Netherrac in the overworld just displays it as a pitch-black block

**To Reproduce**
Place netherrac in the overworld

**Expected Behavior**
It should be the specific unity texture?

**Screenshots**
![2021-05-18_22 11 01](https://user-images.githubusercontent.com/61163736/118709913-41f86d00-b826-11eb-9b78-a9fb0a4629c4.png)

**Additional Context**
Using unity base, unity dark, and unity extras as well as optifine

**Comment by CyanideX** [comment]
This is a Unity: Extras issue, although I understand why it would fit under Unity... _Dark_. 😉 

https://github.com/Unity-Resource-Pack/Unity-Extras/issues/7
