### ISSUE TITLE
[Suggestion] XNet & Cyclic (Both 1.16)

### ISSUE THREAD

**Issue by zappermax** [Unity-Resource-Pack/Unity-Dark#52]
XNet is frequently used in tech-based modpacks as a solution for automating inputs/outputs of various machines. It would be pretty awesome if you could include it in this pack. It uses RFTools as a dependency so if you're gonna work on this I'd recommend you do RFTools first.
[CurseForge page for XNet](https://www.curseforge.com/minecraft/mc-mods/xnet)

Cyclic is basically a random content mod that's included in many modpacks as well.
[CurseForge page for Cyclic](https://www.curseforge.com/minecraft/mc-mods/cyclic)

**Comment by vindocel** [comment]
I'll see if I work on top of the cycle when I have time

**Comment by CyanideX** [comment]
I've tried XNet and it cannot be done because of the stupid GUI system in place.

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity-Dark/pull/19
