### ISSUE TITLE
[1.17.X] Title text in GUIs are unreadable

### ISSUE THREAD

**Issue by nicko302** [Unity-Resource-Pack/Unity-Dark#53]
**Describe the Issue**
Whenever an inventory of any sort is opened (e.g. shulker box, ender chest, chest, etc), the title text at the top of that inventory remains dark grey, so it is unreadable in front of the dark grey GUI background.

**Expected Behavior**
I'm not sure if it is possible, but it would be cool to make this font a brighter colour, so the GUI title can still be read. I did some light research and I'm unsure if it is possible or not.

**Screenshots**
![Issue Screenshot](https://user-images.githubusercontent.com/87546465/126144525-f93cfe8c-39e4-44ff-929a-53d617d2487e.png)
Chest GUI

![Issue Screenshot 2](https://user-images.githubusercontent.com/87546465/126144656-125d672c-c63e-49a8-bebd-c94cea6bc719.png)
Renamed shulker box GUI

**Additional Context**
I do not have any other resource packs enabled and I am using Optifine. I have not tested this without Optifine, though I assume the same issue will be present.

**Comment by CyanideX** [comment]
This might be a 1.17 change. Chest container titles were definitely working in 1.16. I will look into this when I can!
