### ISSUE TITLE
[1.17.X] 2 Random pixels

### ISSUE THREAD

**Issue by ghost** [Unity-Resource-Pack/Unity-Dark#54]
There are 2 random pixels in the recipe menu
![image](https://user-images.githubusercontent.com/67515294/126251130-97405ed1-e7cf-42d7-b17e-9e6456dddfca.png)

**Comment by CyanideX** [comment]
That wasn't there on 1.16 either, I swear! I'm blaming this on 1.17 for now. 😅

**Comment by CyanideX** [comment]
Fixed. Finally.
