### ISSUE TITLE
[1.16] Quark Oddities

### ISSUE THREAD

**Issue by zappermax** [Unity-Resource-Pack/Unity-Dark#55]
Quark Oddities is an addon to Quark (made by the same author).
Currently the backpack, the crate and the matrix enchanting GUI are still light theme.

[CurseForge](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Main page (In the 'Oddities' section)](https://quarkmod.net/#features)

**Comment by CyanideX** [comment]
Oddities doesn't have GUI elements to be made dark. Were you looking for Unity Base support?

**Comment by ChloeDawn** [comment]
Oddities itself is a placebo file, the assets are in Quark itself

**Comment by CyanideX** [comment]
Then we're golden; Quark already completed! 🙂
