### ISSUE TITLE
Support for the Curios Screen

### ISSUE THREAD

**Issue by medtryx** [Unity-Resource-Pack/Unity-Dark#56]
**Suggestion**
Support for the Curios mod would be appreciated. It is used in several mod packs.  Currently when the curios inventory is opened, there is no background to it's item slots. 

![image](https://user-images.githubusercontent.com/17153102/128593925-e9b58cad-33a4-43d1-a13c-cbde8cd3e634.png)

**Comment by CyanideX** [comment]
Curios, the API? I'm going to need more information. 

Which version? What does it look like without Unity? Are any other mods possibly causing this issue? Could you share a download link for the mod?

**Comment by medtryx** [comment]
I set up a Test modpack with only the most recent versions of Forge and [Curios ](https://www.curseforge.com/minecraft/mc-mods/curios)on 1.16.5 and did some testing. It is specifically with Unity Dark and when there are Cosmetic slots for the curios active.  

Curios API only adds slots when the config file is setup for them, I added different slots to a config file without installing other mods to perform these tests. 

With the other Unity resource packs enable, and not Dark this is what it looks like:

![image](https://user-images.githubusercontent.com/17153102/128630033-b30c0239-0014-491c-9368-1f0b7d4ac79a.png)

With Unity Dark active at the top of the load order (also if Unity Dark is the only extra resource pack active) this is what it looks like:  

![image](https://user-images.githubusercontent.com/17153102/128630109-14b48f38-9047-45bd-ad2f-dc811f753283.png)


With Unity Dark active, and at the bottom of the load order this is what happens. 

![image](https://user-images.githubusercontent.com/17153102/128630057-f265b21c-2d61-4a43-a1a5-a55f3fc6895b.png)

With the cosmetic slots disabled it appears to work correctly.

![image](https://user-images.githubusercontent.com/17153102/128630477-59a224a9-2c3c-4a7e-86d7-b298a4ebad5e.png)


This is what it looks like with no resource packs added.

![image](https://user-images.githubusercontent.com/17153102/128630215-b5317129-8410-4355-8c25-577ebd87e1f4.png)

**Comment by CyanideX** [comment]
Fixed in 551487f
