### ISSUE TITLE
[1.16] Applied Energistics 2 Wireless Terminals

### ISSUE THREAD

**Issue by 1mphuls3** [Unity-Resource-Pack/Unity-Dark#57]
I would like to see support for Applied Energistics 2 Wireless Terminal, Ae2 already has support, but wireless terminals doesn't

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge

**Comment by vindocel** [comment]
I added it in the liner that says I'm just waiting to approve it, but I did it for the most recent [AE2WT](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals)

if you want to test just download before they accept just download in this [Fork](https://github.com/vindocel/Unity-Dark)

just download and zip remember to remove the files before doing
.github
.gitattributes
.gitignore
README.md

**Comment by CyanideX** [comment]
Done in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/f20c82bd0c6e0ea879ae8150fc42cfef35e8d296 and https://github.com/Unity-Resource-Pack/Unity-Dark/commit/d4f620f3abbb14a7669d9d3a227e211ea8eba6db
