### ISSUE TITLE
Includes a ghast texture for some reason?

### ISSUE THREAD

**Issue by SpicerXD** [Unity-Resource-Pack/Unity-Dark#63]
I thought this was purely a GUI reskin. So it seemed odd.

**Comment by CyanideX** [comment]
Ghast was already removed in my [previous commit](https://github.com/Unity-Resource-Pack/Unity-Dark/commit/da20dc9a7fd76537adffb2febb0b3b93f4bc949b). Next Curse release will have that change.

**Comment by CyanideX** [comment]
You can download the latest build from GitHub actions: 

https://github.com/Unity-Resource-Pack/Unity-Dark/actions/runs/1254357019
