### ISSUE TITLE
[1.16.5] Create's recipe in JEI looks out of place

### ISSUE THREAD

**Issue by horeaper** [Unity-Resource-Pack/Unity-Dark#71]
**Describe the Issue**
Create's recipe (Mechanical Crafter, Mechanical Press, Mechanical Mixer, etc) in JEI

**To Reproduce**
View any Create's recipe in JEI

**Screenshots**
![2022-02-01_22 21 54](https://user-images.githubusercontent.com/2276325/151986641-70a7be9f-5aa9-441e-b160-327472ef7809.png)
![2022-02-01_22 22 23](https://user-images.githubusercontent.com/2276325/151986770-a9d338ea-49c2-405a-ac35-56ccadae3880.png)

**Expected Behavior**
The "Item Slot" background should be darkened, like everyone else.

**Additional Context**
Forge: 1.16.5-36.2.22
Create: 0.3.2g
Flywheel: 0.2.5
JEI: 7.7.1.138
No OptiFine, no Magnesium, no other resource pack used.

**Comment by CyanideX** [comment]
You can try downloading the latest build from this repo here:
https://github.com/Unity-Resource-Pack/Unity-Dark/actions/runs/1670368966

That should contain the Create JEI support.

![image](https://user-images.githubusercontent.com/3106700/152099294-996991e2-3600-48ea-b419-ae2bb27f80bc.png)

I will release an update on Curse as soon as I can.
