### ISSUE TITLE
[Suggestion] Support for Sophisticated Backpacks

### ISSUE THREAD

**Issue by IsXGeo** [Unity-Resource-Pack/Unity-Dark#72]
**Suggestion**
Please consider adding support for Sophisticated Backpacks.
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

Thanks,

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/6ed065abadfa87c238ff2c5825f323df9e69bdf5

Done!
