### ISSUE TITLE
[1.18.2] Multiple Mods

### ISSUE THREAD

**Issue by Reisanji** [Unity-Resource-Pack/Unity-Dark#73]
**Suggestion**
I love this dark UI design and hope your script can easily support these and any more I might come across.
Thank you.

[Cooking for Blockheads](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Pollution of the Realms](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms)
[Simply Backpacks](https://www.curseforge.com/minecraft/mc-mods/simply-backpacks)
[Moving Elevators](https://www.curseforge.com/minecraft/mc-mods/moving-elevators)
[Chisels & Bits](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
[Alchemistry](https://www.curseforge.com/minecraft/mc-mods/alchemistry)
[Re-chiseled](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Diet](https://www.curseforge.com/minecraft/mc-mods/diet) {Just the inventory button seems wrong}
![Diet_Button](https://user-images.githubusercontent.com/53265963/160264749-bac4ce16-861c-4297-a107-53d285fa4069.png)
![Diet_Screen](https://user-images.githubusercontent.com/53265963/160264753-62ad2b7c-6379-4933-b07b-48d10f394b59.png)

[Copperized](https://www.curseforge.com/minecraft/mc-mods/copperized) {Waxing page in JEI}
![Copperized_Waxing_JEI](https://user-images.githubusercontent.com/53265963/160265185-c77b59cd-5338-4738-a197-1b70b65af6bf.png)

I can grab more screenshots if needed later.

**Comment by CyanideX** [comment]
![image](https://user-images.githubusercontent.com/3106700/160266150-2c6ebf58-1415-4646-8b64-78633ffa0e4b.png)

Oh boy. This one doesn't work. They stretch the GUI background which also stretches the noise. Might need to go noise-less. 😝

**Comment by Reisanji** [comment]
hah now that you mentioned it I can see it, I was just happy that it was dark and kinda matched the inventory screen.

**Comment by CyanideX** [comment]
Cooking for Blockheads: Done.
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/098463c8969d3fc41e58e9518169b77aa67bc272

Diet: Done.
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/ab704f2095d073d0cfa8bd0236c937ab492dd8be

Chisels and Bits: Done.
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/ccad8b77e70bef3fe8d60d5a5713b5266b19c066

Alchemistry: Done.
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/833d06a259f723d14cd4a395e79ff9ba246cb2e3

Rechiseled: Done.
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/5c457ed62ba2772d216e3594e4f02931958e17e3

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity-Dark/actions/runs/3004270803

Test this build, if you'd like. 😃

**Comment by CyanideX** [comment]
Side note: Please submit these as separate issues/suggestions next time.
