### ISSUE TITLE
[1.18.2] Quark settings

### ISSUE THREAD

**Issue by INooBTooMuch** [Unity-Resource-Pack/Unity-Dark#75]
The marks (✔, ❌, ✏️) don't show in the Quark settings menu in-game

**Expected Behavior**
Should be visible

**Additional Context**
I have Quark (mod) installed and also Stay True (resource pack), if I put Stay True above Unity-dark the minecraft settings (the esc screen and the options there) become normal minecraft textured together with Quark but the images are still missing.

Minecraft 1.18.2
Unity-dark 0.8.1
Quark 3.2-358

![quark](https://user-images.githubusercontent.com/107572028/178942447-11d9e85f-1a12-452d-86ab-7fe9a019db54.png)

**Comment by CyanideX** [comment]
Finally fixed and will be releasing an updated version soon.
