### ISSUE TITLE
[Suggestion] Support for Extended Crafting

### ISSUE THREAD

**Issue by NyanMC** [Unity-Resource-Pack/Unity-Dark#76]
**Suggestion**
link: [https://www.curseforge.com/minecraft/mc-mods/extended-crafting](url)
recently i've tried the unity series in modded, and i'm enjoying it, however one mod that has stood out to me as far as lack of darkmode support has been extended crafting. as a brief summary, extended crafting adds larger crafting stations (and automatic versions of them with a few more gui elements) as well as a quantum compressor. there is also the ender crafting, which while it could maybe be tweaked to be darker i can't think of an easy way to modify it, as it's green as opposed to white (though it could just be altered to match the rest of the dark guis, so that it doesn't look weird in JEI).

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/107305910ab404f9881b0ad645b315f2f33a27d5

Done!
