### ISSUE TITLE
[Suggestion] Add support to Trinkets mod.

### ISSUE THREAD

**Issue by IntMarco** [Unity-Resource-Pack/Unity-Dark#77]
Suggest adding support for the **Trinkets** mod and its slots.
[Link to the mod](https://www.curseforge.com/minecraft/mc-mods/trinkets)

**Comment by CyanideX** [comment]
https://github.com/Unity-Resource-Pack/Unity-Dark/commit/772e1433280d9f6a67cdd270317551dbe06aebfd

Done!
