### ISSUE TITLE
[1.14.4] Silentgear

### ISSUE THREAD

**Issue by Boomflex** [Unity-Resource-Pack/Unity-Dark#8]
![image](https://user-images.githubusercontent.com/22868795/70565580-57299080-1b8a-11ea-8b5d-0168e9cda99d.png)

**Comment by CyanideX** [comment]
Any chance you could include the download link for the mods in each issue? 😝 It would make my life so much easier.

**Comment by Boomflex** [comment]
Download: https://www.curseforge.com/minecraft/mc-mods/silent-gear/download/2832435
