### ISSUE TITLE
[1.18.2] Iron Furnace names are dark

### ISSUE THREAD

**Issue by INooBTooMuch** [Unity-Resource-Pack/Unity-Dark#80]
**Describe the Issue**
The names of the furnaces are almost unreadable.

**Screenshots**
![2022-09-07_10 31 40](https://user-images.githubusercontent.com/107572028/188817252-be64d5e6-edf6-4193-823e-bbc2eda83cc8.png)

**Additional Context**
I did just update to the new version (Unity-1.18.X-Dark-0.9.0).

**Comment by CyanideX** [comment]
Fixed and also updated the GUI widgets to look a little nicer.

https://github.com/Unity-Resource-Pack/Unity-Dark/commit/0715d85fa4ee2eacd4013bd1c1d038aa84d4f3e1
