### ISSUE TITLE
[1.18.2] Villager Names for modded villagers aren't visible

### ISSUE THREAD

**Issue by INooBTooMuch** [Unity-Resource-Pack/Unity-Dark#82]
**Describe the Issue**
Villagers from mods ([More Villagers](https://www.curseforge.com/minecraft/mc-mods/more-villagers)) have dark names and aren't visible

**Expected Behavior**
Should be a lighter color like the vanilla ones

**Screenshots**
![2022-09-25_15 47 32](https://user-images.githubusercontent.com/107572028/192144123-86f30413-3469-45fb-b0b7-076d2b88597d.png)

**Additional Context**
I have [Stay True](https://www.curseforge.com/minecraft/texture-packs/stay-true) and the compat one but they are both bellow the Unity Dark one. Also no optifine.

**Comment by CyanideX** [comment]
Added lang support in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/fc3a704c52c6f72480bca5cceaa90df8a4aeeb93

Download the build here: https://github.com/Unity-Resource-Pack/Unity-Dark/actions/runs/3123075938
