### ISSUE TITLE
[1.18.2] Mekanism process bar

### ISSUE THREAD

**Issue by collectchicken** [Unity-Resource-Pack/Unity-Dark#83]
Mekanism machine process bar at the wrong position

it happen both JEI recipe and Mekanism machines themselves
![2022-10-13_18 01 45](https://user-images.githubusercontent.com/115702602/195569640-d5221924-f438-495b-acf1-597e66b56ec4.png)
![2022-10-13_18 02 05](https://user-images.githubusercontent.com/115702602/195569605-d6508076-c54b-4195-ba59-b7805186c2f6.png)
![2022-10-13_18 01 33](https://user-images.githubusercontent.com/115702602/195569618-be70ba45-e1ec-46ec-844d-33de1c9b6210.png)
![2022-10-13_18 01 40](https://user-images.githubusercontent.com/115702602/195569628-151b5f44-b126-4e27-9ea0-34d341dc5dba.png)
![2022-10-13_18 02 01](https://user-images.githubusercontent.com/115702602/195569650-86670b7b-f151-4648-8adb-46091c6d25e2.png)

**Comment by Jimmy-sheep** [comment]
In addition, there's some icons, buttons, tabs and warning part need to be add and update.

**Comment by vindocel** [comment]
hello friend, I already implemented these hearts and others that involve the mechanism such as the reactor guides
I'm just waiting for them to implement the changes I made to the project ------> #87 

while waiting for approval, you can download with these modifications and test and say if everything is ok in this --->[fork](https://github.com/vindocel/Unity-Dark)<--- that I made and just compress the file in zip removing it

.github
.gitattributes
.gitignore
README.md

**Comment by CyanideX** [comment]
Fixed in 1.19 versions. https://github.com/Unity-Resource-Pack/Unity-Dark/commit/d814d0296e49060e8a6634c2f9f2c297d3a8a69e
