### ISSUE TITLE
[1.18.2] Apotheosis

### ISSUE THREAD

**Issue by INooBTooMuch** [Unity-Resource-Pack/Unity-Dark#84]
**Suggestion**
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) had been suggested back in 2019 by another user in #5 , but they have added quite more in the recent 5.7.0 version of the mod and I thought I should make another post about it.
I believe that only the enchanting table (unless vanilla isn't changed with Unity Dark), the fletching table, the 2 library blocks and the new reforging and salvaging tables need the dark theme.

I'm not sure if all of the above can be changed to be dark themed but I thought I should re-suggest the mod.

**Comment by CyanideX** [comment]
Done: https://github.com/Unity-Resource-Pack/Unity-Dark/commit/c2387030046db680c016131e245c71643006387a

Download the build here: https://github.com/Unity-Resource-Pack/Unity-Dark/suites/8765919854/artifacts/397485676
