### ISSUE TITLE
[1.18.2] Quark Crate "Labeling" is Dark

### ISSUE THREAD

**Issue by INooBTooMuch** [Unity-Resource-Pack/Unity-Dark#85]
**Describe the Issue**
I can't really describe is but there is a picture.

**Screenshots**
![2022-10-30_11 51 46](https://user-images.githubusercontent.com/107572028/198872698-65d001e1-40d7-4ed3-83f6-43963e49bfb9.png)

The letters are darker than what they should be.
Minor issue so low priority.

**Comment by CyanideX** [comment]
Are you sure this crate is from Quark? I don't see it when I have Quark installed, just the food crates: 
![image](https://github.com/Unity-Resource-Pack/Unity-Dark/assets/3106700/08cdcbc6-130d-41de-8ba9-7c688c678eec)

**Comment by CyanideX** [comment]
Oh, this appears to be the storage crate from Quark Oddities.

**Comment by CyanideX** [comment]
Fixed in 1.19 versions.
