### ISSUE TITLE
[1.19.2] Applied Energistics 2 UI doesn't change

### ISSUE THREAD

**Issue by Ashendale** [Unity-Resource-Pack/Unity-Dark#86]
Accessing AE2 interfaces loads them with the default (white) GUI. I've tested this on my custom pack, as well as a pack using only AE2.

To Reproduce
Steps to reproduce the behavior or see the issue:
1: Start MC and enable resource packs before creating a world (I did this on a new instance; resource pack order is same, barring Twilight Forest and Mod Resources, which were not listed).

![image](https://user-images.githubusercontent.com/14125391/202300544-78c847b5-9d58-443f-a1f2-b2155f0038aa.png)

2: Go into world and interact with machinery/objects.

![image](https://user-images.githubusercontent.com/14125391/202300674-5492d860-f46f-4075-802f-e19773370b20.png)

3: Cry bitter tears from being blinded by the white GUI background.

Expected Behavior
I expected a background similar to that of Mekanism GUIs.

Additional Details
This was tested with the ME Crafting Terminal, ME Interface, ME Export Bus, ME Controller, and ME Drive. All produce the same result.

**Comment by Ashendale** [comment]
Looking into the texture folder and comparing to that of the AE2 mod, I notice there are missing GUI files. Still, I do not understand why the ones that are there do not override the default files. I have no idea how this is supposed to work, but I thought that I could help with a bit more info.

If anything else, please let me know.

**Comment by vindocel** [comment]
this is due to the folder that Applied abbreviates to ae2 and just change it, I already sent the changes, they just need to review and accept

**Comment by Ashendale** [comment]
I think I tried that and it didn't work? Maybe I did something else as well and borked it. Going to do it now and confirm/deny.

**Comment by Ashendale** [comment]
Changing the `/assets/Applied Energistics 2/` folder name to ae2 makes it so I cannot even open the GUIs by interacting. There may be something more to this than just changing the name.

**Comment by vindocel** [comment]
it's no use just changing the name of the folder, you have to change the name and also change the configuration inside the file "/screens/common/palette.json
" and also add the new guis that were implemented in the recent ae2 updates

I already made all these changes and tested them, I'm just waiting for them to see the test and approve

you can check the changes here ----> #87

**Comment by Ashendale** [comment]
Yeah, that fork seems to be working just fine. I'll close that and go over there if I find anything wrong. Thanks for the helps.
