### ISSUE TITLE
[1.19.2] Apotheosis Tweaks

### ISSUE THREAD

**Issue by Maltshakes** [Unity-Resource-Pack/Unity-Dark#89]
I'm using this build here: https://github.com/Unity-Resource-Pack/Unity-Dark/suites/8765919854/artifacts/397485676

While testing the 1.18 version in 1.19.2, I noticed some issues with text being too dark.
"Fletching"
![image](https://user-images.githubusercontent.com/76584081/208637782-89934d67-1831-4915-852c-d84b5b4bd20f.png)

"Reforge"
![image](https://user-images.githubusercontent.com/76584081/208637843-1c0ff14c-ee29-4d99-8eba-e8b2b75950d0.png)

"Salvage" "Results"
![image](https://user-images.githubusercontent.com/76584081/208637904-e96d3b20-416a-4f03-a97a-af96afbd384c.png)

"Library of Alexandria" "Name Filter" "Item Filter"
![image](https://user-images.githubusercontent.com/76584081/208638024-579f3d0f-75a1-4743-86a1-377d4e519c8e.png)

**Comment by CyanideX** [comment]
Fixed in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/c39ecf8c6952b8110c5004f2bdb7fd6d97c024ad
