### ISSUE TITLE
[Suggestion] Farmer's Respite support

### ISSUE THREAD

**Issue by Maltshakes** [Unity-Resource-Pack/Unity-Dark#90]
**Suggestion**
Please add support for Farmer's Respite: https://www.curseforge.com/minecraft/mc-mods/farmers-respite

Specifically they have a kettle that has a UI
![image](https://user-images.githubusercontent.com/76584081/208640795-23c75fc2-33bd-41a0-a07e-9dd668f0671e.png)

**Comment by CyanideX** [comment]
Done in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/7564e8f42225de2b8a5f2824ea4ecaac8460a808
