### ISSUE TITLE
[1.19.3] Broken 1.19.3 creative inventory texture

### ISSUE THREAD

**Issue by KidOfCubes** [Unity-Resource-Pack/Unity-Dark#92]
**Describe the Issue**
A clear and concise description of what the issue is.
Un-updated texture for 1.19.3 creative inventory

**To Reproduce**
Steps to reproduce the behavior or see the issue:
- Download and apply the (0.9.1 [1.19.X]) version of Unity Dark from CurseForge
- Open the creative inventory menu

**Expected Behavior**
A clear and concise description of what you expected to see.
I expected to not see a bugged menu in the creative inventory screen

**Screenshots**
Latest version as of writing (0.9.1 [1.19.X]) (which claims to support 1.19.3 in CurseForge)

What the creative menu looks like (broken)
![image](https://user-images.githubusercontent.com/40485669/210132847-7476b2c6-86b7-412d-bcbc-c37ea4647803.png)

What the creative menu *should* look like (fixed)
![image](https://user-images.githubusercontent.com/40485669/210132647-941aaac3-abb6-4a4e-8cea-c6d39bbee1ba.png)
(quick image fix I made in paint)

**Additional Context**
Do you happen to have any mods installed? Many
Do you have any other resource packs enabled? Yes (Unity dark is on top in the list though)
Are you using OptiFine? No
I was able to fix it with a quick image edit on /assets/minecraft/textures/gui/container/creative_inventory/tabs.png so I doubt its a mod related issue.

**Comment by KidOfCubes** [comment]
#93

**Comment by CyanideX** [comment]
Sorry, I didn't realize that you had submitted a PR already! I'm really bad at keeping up with Unity updates these days. Sorry. 😩
