### ISSUE TITLE
[1.19.3] 2 White pixels

### ISSUE THREAD

**Issue by DeanyBox** [Unity-Resource-Pack/Unity-Dark#95]
**Describe the Issue**
There is a pixel colored incorrectly i believe. it looks very off if this was intentional. There are 2 white pixels for the crafting book. It is bugging the heck out of me.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/29419049/215302967-589abb51-0f68-4d24-a6d4-a2c298b832a6.png)

**Comment by CyanideX** [comment]
This was fixed in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/64aa3d3c05cbbf496bb9db76e7c5e5c61c88e05f but I haven't released an update on Curse. Try downloading a build from [here](https://github.com/Unity-Resource-Pack/Unity-Dark/suites/10366002637/artifacts/511124056).
