### ISSUE TITLE
[1.18.2] Refined Storage Pattern Grid is a little off centered

### ISSUE THREAD

**Issue by INooBTooMuch** [Unity-Resource-Pack/Unity-Dark#96]
**Describe the Issue**
The output in the pattern grid is a little off to the side where the actual items should be

**To Reproduce**
1. Open the pattern grid of  Refined storage
2. Mouse over the slots

**Screenshots**
![2023-02-14_12 55 16](https://user-images.githubusercontent.com/107572028/218717236-a8d5c0ad-0d0b-49e8-9790-0b635c7443ca.png)

**Additional Context**
I have Refined Storage 1.10.5 and some addons but the Pattern grid is added by the base mod
(Refined Storage Addons, Refined Storage: Requestify and ExtraStorage are the addons)

**Comment by CyanideX** [comment]
Fixed in 1.19 versions.
