### ISSUE TITLE
[Suggestion] 1.12.2 JEI Support 

### ISSUE THREAD

**Issue by vizthex123** [Unity-Resource-Pack/Unity-Dark#97]
**Suggestion**
It'd be great if JEI got supported in 1.12.2. Feels kinda weird that it isn't there by default since it's the go-to recipe viewer mod.

Support for [Scannable](https://www.curseforge.com/minecraft/mc-mods/scannable) and [Iron Backpacks](https://www.curseforge.com/minecraft/mc-mods/iron-backpacks) would also be noice.

**Comment by vizthex123** [comment]
_oof_, there's not an update for 1.12.2 :c

**Comment by CyanideX** [comment]
1.12 is 6 years old.

**Comment by vizthex123** [comment]
well yeah, but it's still great.

also specifically ask for it in this issue lol

**Comment by CyanideX** [comment]
Sorry, I just don't have time to work on older versions at the moment.

**Comment by vizthex123** [comment]
fair enough. Hope someone makes an add-on or something.
