### ISSUE TITLE
Suggestion: Compact Storage

### ISSUE THREAD

**Issue by BUBUSTEIN13** [Unity-Resource-Pack/Unity-Dark#98]
**Suggestion**
Add support for Compact Storage: https://www.curseforge.com/minecraft/mc-mods/compactstorage

**Comment by CyanideX** [comment]
Done. 

https://github.com/Unity-Resource-Pack/Unity-Dark/commit/4441f33aa68082aee33f3b2825cf2aa0f25d0876

**Comment by CyanideX** [comment]
Download build here: https://github.com/Unity-Resource-Pack/Unity-Dark/actions/runs/4663612981
